In [38]:
import numpy as np#creating numpy/nd arays

In [39]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [40]:
type(arr1)

numpy.ndarray

In [41]:
arr2 = np.array([[1,2,3],[3,4,5]])
arr2

array([[1, 2, 3],
       [3, 4, 5]])

In [42]:
type(arr2)

numpy.ndarray

In [43]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
arr4 = np .ones((4,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [46]:
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
arr6 = np.arange(2,10,2)
arr6

array([2, 4, 6, 8])

In [48]:
arr7 = np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [49]:
arr8 = arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [50]:
arr1.shape

(5,)

In [51]:
arr2.shape


(2, 3)

In [52]:
arr9 = np.array([[[1,2],[3,4]],[[4,5],[9,3]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [9, 3]]])

In [53]:
arr9.shape


(2, 2, 2)

In [54]:
arr9.ndim

3

In [55]:
arr2.ndim

2

In [56]:
arr9.itemsize

8

In [57]:
arr9.size

8

In [58]:
arr8.dtype


dtype('float64')

In [59]:
arr9.dtype

dtype('int64')

In [60]:
arr9.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[4., 5.],
        [9., 3.]]])

In [61]:
arr9.dtype

dtype('int64')

In [62]:
lista = range(100)
arr11 = np.arange(100)
import sys
print(sys.getsizeof(87)*len(lista))

2800


In [63]:
len(lista)

100

In [64]:
print(arr11.itemsize*arr11.size)

800


In [65]:
import time

x = range(100000)
y = range(100000, 200000)

start_time = time.time()

c = [(x, y) for x, y in zip(x, y)]  # Create 100,000 tuples

print(time.time() - start_time)


0.018999576568603516


In [66]:
a = np.arange(100000)
b = np.arange(100000,200000)

start_time = time.time()
c = a+b

print(time.time()- start_time)

0.005000591278076172


In [67]:
arr12 = np.arange(24).reshape(6,4)

In [68]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [70]:
arr12[2]

array([ 8,  9, 10, 11])

In [76]:
arr12[:,2]#amller , is for write the column

array([ 2,  6, 10, 14, 18, 22])

In [77]:
arr12[2:4,1:3]#these process are slicing

array([[ 9, 10],
       [13, 14]])

In [78]:
arr12[4:,2:]

array([[18, 19],
       [22, 23]])

In [80]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [81]:
for i in arr12:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
[16 17 18 19]
[20 21 22 23]


In [83]:
for i in np.nditer(arr12):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [86]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])

In [88]:
arr1-arr2

array([-3, -3, -3, -3, -3, -3])

In [89]:
arr1*2

array([ 2,  4,  6,  8, 10, 12])

In [90]:
arr1*arr2

array([ 4, 10, 18, 28, 40, 54])

In [91]:
arr2>5

array([False, False,  True,  True,  True,  True])

In [93]:
arr3= np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)
arr3.dot (arr4)

array([[ 28,  31],
       [100, 112]])

In [94]:
arr4.max()

np.int64(11)

In [95]:
arr4.min()

np.int64(6)

In [96]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [97]:
arr4.min(axis = 0)

array([6, 7])

In [98]:
arr4.min(axis=1)

array([ 6,  8, 10])

In [99]:
arr4.sum(axis=0)

array([24, 27])

In [100]:
arr4.sum(axis=1)

array([13, 17, 21])

In [101]:
arr4.mean()

np.float64(8.5)

In [102]:
arr4.mean(axis=0)

array([8., 9.])

In [103]:
arr4.std()

np.float64(1.707825127659933)

In [105]:
np.sin(arr4)

array([[-0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849],
       [-0.54402111, -0.99999021]])

In [106]:
np.median(arr4)

np.float64(8.5)

In [107]:
np.exp(arr4)

array([[  403.42879349,  1096.63315843],
       [ 2980.95798704,  8103.08392758],
       [22026.46579481, 59874.1417152 ]])

In [108]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [110]:
arr4.ndim#dimention

2

In [114]:
arr4.ravel()#change all the arry to 1D

array([ 6,  7,  8,  9, 10, 11])

In [116]:
arr4.transpose()#exchange row and column


array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [117]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

arr5 = np.arange(12,13).reshape(2,3)

In [122]:
arr5 = np.arange(12,18).reshape(2,3)
arr5




array([[12, 13, 14],
       [15, 16, 17]])

In [124]:
np.hstack((arr3,arr5))#hstack means stack matrix horizontally 

array([[ 0,  1,  2, 12, 13, 14],
       [ 3,  4,  5, 15, 16, 17]])

In [128]:
np.hsplit(arr3,3)#split horizontaly

[array([[0],
        [3]]),
 array([[1],
        [4]]),
 array([[2],
        [5]])]

In [129]:
#like this v stack is for verticaql stack v split means vertical split


In [130]:
arr8 = np.arange(24).reshape(6,4)
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [131]:
arr8[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [176]:
arr = np.random.randint(low = 1,high = 100,size= 20).reshape(4,5)
arr

array([[38, 52, 56, 91, 41],
       [85, 66, 91, 86, 70],
       [88, 10, 75, 68, 55],
       [43, 10, 63,  4, 34]], dtype=int32)

In [177]:

arr>30


array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True, False,  True, False,  True]])

In [178]:
arr[arr>30]

array([38, 52, 56, 91, 41, 85, 66, 91, 86, 70, 88, 75, 68, 55, 43, 63, 34],
      dtype=int32)

In [179]:
arr78 = np.random .randint(low = 1,high =  100,size =1).reshape(1,1)

In [180]:
arr78

array([[8]], dtype=int32)

In [181]:
arr[(arr>50) & (arr%2 != 0)]

array([91, 85, 91, 75, 55, 63], dtype=int32)

In [182]:
arr[(arr>50) & (arr%2 != 0)]=0
arr

array([[38, 52, 56,  0, 41],
       [ 0, 66,  0, 86, 70],
       [88, 10,  0, 68,  0],
       [43, 10,  0,  4, 34]], dtype=int32)

In [4]:
x = np.linspace(-40,40,100)
x

array([-40.        , -39.19191919, -38.38383838, -37.57575758,
       -36.76767677, -35.95959596, -35.15151515, -34.34343434,
       -33.53535354, -32.72727273, -31.91919192, -31.11111111,
       -30.3030303 , -29.49494949, -28.68686869, -27.87878788,
       -27.07070707, -26.26262626, -25.45454545, -24.64646465,
       -23.83838384, -23.03030303, -22.22222222, -21.41414141,
       -20.60606061, -19.7979798 , -18.98989899, -18.18181818,
       -17.37373737, -16.56565657, -15.75757576, -14.94949495,
       -14.14141414, -13.33333333, -12.52525253, -11.71717172,
       -10.90909091, -10.1010101 ,  -9.29292929,  -8.48484848,
        -7.67676768,  -6.86868687,  -6.06060606,  -5.25252525,
        -4.44444444,  -3.63636364,  -2.82828283,  -2.02020202,
        -1.21212121,  -0.4040404 ,   0.4040404 ,   1.21212121,
         2.02020202,   2.82828283,   3.63636364,   4.44444444,
         5.25252525,   6.06060606,   6.86868687,   7.67676768,
         8.48484848,   9.29292929,  10.1010101 ,  10.90

In [11]:
y = np.sin(x)



In [12]:
import  numpy as np

In [13]:
import matplotlib.pyplot as plt
%matplotlib inline

In [14]:
plt.plot(x,y)

[<matplotlib.lines.Line2D at 0x141c8mll5700>]

In [15]:
y.size

100

In [18]:
y = x*x+2*x


In [19]:
plt.plot(x,y)

In [21]:
a1 = np.arange(8).reshape(2,4)
a2 = np.arange(8,16).reshape(2,4)
print(a1,a2)

[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]


In [22]:
#important functions for data science

In [23]:
np.random.random()

0.5402910309193403

In [27]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [28]:
np.random.uniform(3,10)

8.042271454095108

In [29]:
np.random.uniform(1,100,10)

array([ 1.01132311, 30.93092469, 15.52883319, 10.14152088, 19.43976093,
       35.21051198, 40.27997995, 54.34285667, 42.50025693, 68.83673054])

In [31]:
np.random.uniform(1,100,10).reshape(5,2)

array([[32.02899364, 69.53993895],
       [87.76252608, 89.56605969],
       [ 9.41937693,  4.86642354],
       [17.81321154, 87.93610784],
       [10.73633655, 42.68965488]])

In [49]:
arrr = np.array([3,2,6,1,7,4,9])
arrr

array([3, 2, 6, 1, 7, 4, 9])

In [52]:
np.sort(arrr)

array([1, 2, 3, 4, 6, 7, 9])

In [54]:
np.percentile(arrr,9)

np.float64(1.54)